name: Fetch Web pages
on:
  issues:
    types:
      - labeled
jobs:
  Fetch-and-Save:
    if: github.event.label.name == 'crawler'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - uses: freeCodeCamp-China/article-webpage-to-markdown-action@v1
        with:
          newsLink: "${{ github.event.issue.Body }}"
          markDownFilePath: "./translation/"
          githubToken: ${{ github.token }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "${{ github.event.issue.title }}"

      - name: Lark notification
        uses: foxundermoon/feishu-action@v2
        with:
          url: ${{ secrets.LARK_CHATBOT_HOOK_URL }}
          msg_type: post
          content: |
            post:
              zh_cn:
                title: 开源文库 GitHub 文章爬取
                content:
                  - - tag: text
                      text: Issue
                    - tag: a
                      text: #${{ github.event.issue.number }}
                      href: ${{ github.server_url }}/${{ github.repository }}/issue/${{ github.event.issue.number }}
